# Basic `dependabot.yml` file with
# minimum configuration for two package managers

version: 2
updates:
  - package-ecosystem: github-actions
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    assignees:
      - yamatt
    labels:
      - dependabot
      - docker

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    assignees:
      - yamatt
    labels:
      - dependabot
      - docker
