name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test upload
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          key_id: ${{ secrets.B2_KEY_ID }}
          application_key: ${{ secrets.B2_APPLICATION_KEY }}
          bucket_name: ${{ secrets.B2_BUCKET_NAME }}
          file_path: action.yml
          remote_path: test
